### ISSUE TITLE
saves the image in low resolution

### ISSUE THREAD

**Issue by josephresearcher** [uqrmaie1/admixtools#12]
Hello
Dear Maier
This option saves the image in low resolution
Can it be stored at a higher resolution?

![43](https://user-images.githubusercontent.com/74604571/131223348-4df3701d-5d36-418b-a7c0-8927fe710d0a.png)

**Comment by uqrmaie1** [comment]
That's an inbuilt feature from plotly, and I don't think I can change that on my end. If you want to save a plot of the graph in higher resolution, you could download the graph as text file, load it in R using the command line function `read_table2()`, plot it with `plot_graph()`, and then `ggsave()`, specifying the `height` and `width` parameters.

**Comment by josephresearcher** [comment]
Dear 
Thank you very much
For answering questions 
 Robert Maier
