### ISSUE TITLE
Stop quickly when package is required but not installed.

### ISSUE THREAD

**Issue by privefl** [uqrmaie1/admixtools#16]
Just a simple suggestion, e.g. in `packedancestrymap_to_plink()`, package {genio} is required 
https://github.com/uqrmaie1/admixtools/blob/0a7ca2f26ddcb3cf606e9a967e61464a3125bfb5/R/io.R#L2100
but the user get the error that this package is not installed after having read the full data in memory (which can take time).

It would be useful to test if this package is installed at the very beginning of the function.

**Comment by uqrmaie1** [comment]
Thanks for the suggestion, the latest version should fail earlier if that package isn't installed!
