### ISSUE TITLE
Error when running eigenstrat_to_plink

### ISSUE THREAD

**Issue by CLeib** [uqrmaie1/admixtools#17]
Hi,

I'm trying to extract a sample from multi-sample eigenstrat files (.geno, .ind, .snp) from David Reich's lab and convert to plink with $eigenstrat_to_plink, but ran into some difficulties. 

the command I use is
$eigenstrat_to_plink("full230", "CHIMP", inds=c("Chimp"))

At first it seems that it's working, but then I get an error:

ℹ full230.geno has 235 samples and 1233632 SNPs.
ℹ Reading data for 1 samples and 1233632 SNPs
ℹ Expected size of genotype data: 148 MB
1233k SNPs read...
✔ 1233632 SNPs read in total
Error in if (nrow(bim) != m) stop("Num loci in X (", m, ") and bim (",  :
  argument is of length zero

I'm having trouble understanding what is wrong, and it could be fixed.

Many thanks,
Chen

**Comment by uqrmaie1** [comment]
Thanks for pointing this out!
The error was caused by unexpected behavior when selecting a single sample with `inds`. It should work now!

**Comment by CLeib** [comment]
Great, thanks!
