### ISSUE TITLE
No SNPs remain!

### ISSUE THREAD

**Issue by fraser-combe** [uqrmaie1/admixtools#2]
I keep getting a warning message when running extract_f2 via the command line or using run shiny tools
I am using a eigenstrat file which was converted from a vcf using convertVCFtoEigenstrat.sh
warning:Error in discard_from_aftable: No SNPs remain! Increase maxmiss or select fewer populations

I have tried selecting maxmiss =1 
and only 3 populations with around 10 individuals in but for some reason no success, do you have any recommendations?

**Comment by SethMusker** [comment]
Hi @fraser-combe I am getting the same error but with plink data. I can read in the data fine, and the genotyping rate is complete (i.e. zero missingness).

Did you figure it out?

**Comment by SethMusker** [comment]
@uqrmaie1

**Comment by SethMusker** [comment]
Ok it's working. Had to set `auto_only = FALSE`

**Comment by bingli8899** [comment]
Hi all, I run into the same problem and after setting to auto_only = False, I still got the error that no SNP remainning. I also set maxmiss = 1.0 already. Any ideas?
