### ISSUE TITLE
graph_plusone() error: Error in degree(graph, mode = "in") : Not a graph object

### ISSUE THREAD

**Issue by rturba** [uqrmaie1/admixtools#21]
Hello,

I'm not sure what is going on here with this error. I'm simply trying to run the example code in the documentation:

`newgraphs = graph_plusone(example_graph)`

and I'm getting the above error:

`Error in degree(graph, mode = "in") : Not a graph object`

When I look at `example_graph`, I see:

```
# A tibble: 27 x 2
   from  to                  
   <chr> <chr>               
 1 R     Chimp.REF           
 2 R     N4N                 
 3 N0N   Altai_Neanderthal.DG
 4 N0N   N3N0                
 5 N1N   N0N                 
 6 N1N   N3N1                
 7 N2N0  N1N                 
 8 N2N0  N3N6                
 9 N2N1  Vindija.DG          
10 N2N1  N2N3                
# ... with 17 more rows
```

I've installed admixtools following the commands here:

`devtools::[install_github](https://devtools.r-lib.org/reference/remote-reexports.html)("uqrmaie1/admixtools", dependencies = TRUE)`

And I'm using RStudio v1.3, R v4.0.3 on a Windows 10 machine.

**Comment by uqrmaie1** [comment]
There are two example graph objects loaded when you load the package: `example_graph`, which is in table format, and `example_igraph`, which is in `igraph` format. Some functions only work with graphs in `igraph` format.
Try `newgraphs = graph_plusone(example_igraph)`!

**Comment by rturba** [comment]
Ah, ok! Yes, the `example_igraph` works. It should probably be updated in the [admixture page](https://uqrmaie1.github.io/admixtools/articles/graphs.html#graphs-in-admixtools-2-1) though.

**Comment by uqrmaie1** [comment]
You're right, thanks for pointing it out. I fixed that now!
