### ISSUE TITLE
find.graphs error in 'slice_sample'

### ISSUE THREAD

**Issue by mennodejong1986** [uqrmaie1/admixtools#23]
Hello,

Could you help me with resolving the following issue?

I am trying to create admixture graphs using the following commands on a >50K biallelic SNP dataset:

extract_f2(pref="snpdata","admixtoolsfolder",maxmiss=0.1,overwrite=TRUE,auto_only=FALSE)
f2_blocks 	<- f2_from_precomp("admixtools2folder")
find_graphs(data=f2_blocks,numadmix=0)

However, when running the find_graphs function, I encounter the following error:

√ 1: score 7183.76      best score 7183.76      none    tot 1
√ 2: score 6500.704     best score 6500.704     rearrange_negadmix3     tot 9
√ 3: score 6427.452     best score 6427.452     swap_negdrift   tot 19
√ 4: score 6427.451     best score 6427.451     rearrange_negdrift      tot 25
Error in `slice_sample()`:
! Problem while computing indices.
Caused by error in `sample.int()`:
! cannot take a sample larger than the population when 'replace = FALSE'
---
Backtrace:
  1. global findgraph(nadmixture = 3)
 28. base::local(...)
 29. base::eval.parent(substitute(eval(quote(expr), envir)))
 30. [ base::eval(...) ] with 1 more call
 32. [ base::eval(...) ] with 1 more call
 34. dplyr:::sample_int(n, size(n), replace = replace, wt = weight_by)
 35. base::sample.int(n, size, prob = wt, replace = replace)
Run `rlang::last_trace()` to see the full context.

I tried removing certain populations, and setting different values for the numadmix parameter, but the error is persistent, sometimes occurring after a few steps only (like in the example above), sometimes after many steps (i.e, >30).   

Thanks in advance for your help!

Best,

Menno

**Comment by berserker1** [comment]
Any leads?

**Comment by uqrmaie1** [comment]
This should be fixed in the latest version!
Because some of these errors come up only sporadically, the source of the problem can be difficult to track down. Please also post the output of `rlang::last_trace()` and `rlang::last_error()`, if you get an error like that!

**Comment by mennodejong1986** [comment]
Indeed, I don't receive the error anymore. Thanks for your help!
