### ISSUE TITLE
Counterintuitive sign for z-scores in qpgraph

### ISSUE THREAD

**Issue by jeffspence** [uqrmaie1/admixtools#3]
Hello,

The sign of the z-scores reported by `qpgraph()` for the various f-stats seems to be incorrect.  Generally z-scores are defined as (observed - expected) / se.  It appears that in the output of running qpgraph that the z-scores have the opposite sign, as they seem to be: `(fit - est) / se`.  This is in contrast to the output of e.g., `f4` where the z-score is just `est/se`.

Thanks!

**Comment by uqrmaie1** [comment]
Thanks for pointing this out!
I changed it, and now the residuals and z-scores are `est - fit` rather than the other way round.
