### ISSUE TITLE
Suggestion: Running extract_f2 for a very large dataset (600 ind. x 18,000,000 snp)

### ISSUE THREAD

**Issue by wjaratlerdsiri** [uqrmaie1/admixtools#30]
Dear Robert,

I like to extract f2 data from my large genetic data for 9 populations. So far, I am using 8 cpus and not finishing yet. Do you have any suggestions for a run to finish at the quickest time?

Thank you,
Weerachai

**Comment by uqrmaie1** [comment]
`extract_f2` has an `n_cores` parameter, which was ignored until now, but in the most recent version, it should actually parallelize the computations. The f2 computations are split into chunks, and the size of chunks is proportional to `maxmem/n_cores`. So you could set `n_cores` to however many cores you want to use and play around with `maxmem` to see what works best.

Setting `fst = FALSE` will also speed things up. Unlike `f2`, `fst` isn't used for any other computations.

**Comment by wjaratlerdsiri** [comment]
Thank you so much for a prompt reply! It worked well with 200 GB memory.

Cheers,
