### ISSUE TITLE
The order of pops in outgroup f3 test

### ISSUE THREAD

**Issue by hungweichen0327** [uqrmaie1/admixtools#54]
Dear @uqrmaie1,

I would like to confirm the order of 3 pops when running outgroup f3 statistics by qp3pop.
As I know, Admixtools2 computes 𝑓3 statistics of the form 𝑓3(𝐴;𝐵,𝐶) and  I would use `qp3pop(f2_blocks, pop1, pop2, pop3)` to do 𝑓3 statistics. I want to confirm the order of the pops.

**In 𝑓3(𝐴;𝐵,𝐶):**
pop1 refer to A
pop2 refer to B
pop3 refer to C

So I should put outgroup in pop1. Is that correct?

Thank you for the help!

**Comment by uqrmaie1** [comment]
Yes, that's correct. In the original qp3Pop, to get **𝑓3(𝐴;𝐵,𝐶)**, you would specify the populations in the order `B, C, A` (source 1, source 2, target), but in Admixtools2, it is `A, B, C` (target, source 1, source 2).

**Comment by hungweichen0327** [comment]
Dear @uqrmaie1,
Thank you for the kind reply. I got it!
