### ISSUE TITLE
please add tags/releases

### ISSUE THREAD

**Issue by jowodo** [uqrmaie1/admixtools#64]
Hi,

adding tags to commits can increase ease of reproducibility because they are more easily human readable. Now, for example, I would not know which commit to reference for version 2. Past commit can be easily tagged:

```
git clone https://github.com/smorabit/hdWGCNA
cd hdWGCNA
git log --graph --oneline # choose commit to tag
git checkout 992d7d1 # 992d7d1 is the chosen commit 
git tag v2.0
git push origin --tags
```

It would be greatly appreciated if you could tag previous versions and/or the latest version. See [this stackoverflow answer](https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository/18223354#18223354) for more info.

Thanks

**Comment by uqrmaie1** [comment]
That's a good suggestion. I have added a tag to the latest commit, and I'll add new tags to future commits.
I'm not sure if it's a good idea to add tags to old commits now. Most major commits have been a while ago, and there are more than 200 commits in total. If there is a particular commit that you are using and you would like me to tag it, please let me know!
