### ISSUE TITLE
Installation / Update error

### ISSUE THREAD

**Issue by AimSmall37** [uqrmaie1/admixtools#77]
>devtools::install_github("uqrmaie1/admixtools")

Downloading GitHub repo uqrmaie1/admixtools@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/uqrmaie1/admixtools/tarball/HEAD' failed

Also tried the following with the same result.

> remotes::install_github("uqrmaie1/admixtools")

Downloading GitHub repo uqrmaie1/admixtools@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/uqrmaie1/admixtools/tarball/HEAD' failed

**Comment by uqrmaie1** [comment]
This is probably not related to admixtools. Does it work when you try to install other packages via `install_github()`?
I see some possible solutions for that error message on StackOverflow that you could try out!

**Comment by AimSmall37** [comment]
https://cran.r-project.org/web/packages/githubinstall/readme/README.html

I tried the githubinstall as well to no avail.  

I saw this line in the link above...

"You may sometimes encounter failing to install packages because its repository **HEAD** is not valid no longer. In such case, you can specify a tag or commit to ref. In most cases, developers add tags on an unbroken commit. For instance, you can install densratio from the [“v0.0.3” tag](https://github.com/hoxo-m/densratio/releases/tag/v0.0.3) as follows:"

I'll keep investigating, I appreciate the quick reply.

R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

**Comment by AimSmall37** [comment]
Ended up downloading the tarball manually and then installing.

install.packages("D:\\Users\\Wilbur\\Downloads\\uqrmaie1-admixtools-v2.0.5-1-g11d0a81.tar.gz", repos=NULL, type="source")

**Comment by AimSmall37** [comment]
Closing ticket.  Thanks for quick response.
