### ISSUE TITLE
Qpadm - Inferred fitted F4 statistics

### ISSUE THREAD

**Issue by Kale-GA** [uqrmaie1/admixtools#81]
Greetings Dr. Maier, 
In issue #48 
https://github.com/uqrmaie1/admixtools/issues/48
You said... "If you want the inferred fitted f4-statistics, I'll have to change a few more things in the qpadm function. It might also slow it down a bit, but maybe it's worth it." 

I don't think I am alone in thinking this would be a highly appreciated addition to admixtools2.
When using admixtools1 any time a qpadm model failed, right away I could scroll down to the gendstats and see why.
If speed is a concern, maybe it could work as a flagged option, like 'print_residuals = TRUE' or such?

As always, much thanks for your great work,
Kale.

**Comment by uqrmaie1** [comment]
Hi Kale, thanks for letting me know that this is an important feature! I made some changes to the `qpadm` function, and `return_f4` should now give you fitted f4-statistics when the input is a genotype file. I haven't tested it much, so please let me know if you find any issues with it!

**Comment by Kale-GA** [comment]
Thanks for addressing the topic so quickly!
Here's a test run...

left = c('BachoKiro_BK1653', 'Sunghir')
right = c('Mbuti', 'ZlatyKun', 'Ust_Ishim', 'BachoKiro_IUP', 'China_UP', 'Onge_Jarawa', 'Kostenki14', 'Goyet_Fournol', 'Muierii1')
target = 'Gravettian'
qpadm("C:/Users/user/Desktop/Dataset/Kale52eQPgraph", left, right, target, return_f4 = TRUE)

Returns in $f4 a 144x9 tibble...
  1 Gravettian BachoKiro_BK1653 BachoKiro_IUP China_UP      -8.31458e-4 0.000461191 -1.80285   7.14117e- 2 790705
  2 Gravettian Sunghir          BachoKiro_IUP China_UP       1.63207e-4 0.000315980  0.516508  6.05499e- 1 790705
  3 Gravettian BachoKiro_BK1653 BachoKiro_IUP Goyet_Fournol  2.61649e-4 0.000572124  0.457328  6.47435e- 1 790705
  4 Gravettian Sunghir          BachoKiro_IUP Goyet_Fournol -1.17146e-3 0.000394313 -2.97089   2.96937e- 3 790705
  5 Gravettian BachoKiro_BK1653 BachoKiro_IUP Kostenki14    -2.68339e-3 0.000617175 -4.34786   1.37472e- 5 790705
  6 Gravettian Sunghir          BachoKiro_IUP Kostenki14     2.55322e-3 0.000454612  5.61625   1.95146e- 8 790705
  7 Gravettian BachoKiro_BK1653 BachoKiro_IUP Mbuti         -4.23729e-5 0.000411702 -0.102921  9.18025e- 1 790705
  8 Gravettian Sunghir          BachoKiro_IUP Mbuti          3.96070e-4 0.000282674  1.40116   1.61167e- 1 790705
  9 Gravettian BachoKiro_BK1653 BachoKiro_IUP Muierii1       1.33839e-3 0.000646783  2.06931   3.85169e- 2 790705
 10 Gravettian Sunghir          BachoKiro_IUP Muierii1      -5.98186e-4 0.000431825 -1.38525   1.65976e- 1 790705
 11 Gravettian BachoKiro_BK1653 BachoKiro_IUP Onge_Jarawa   -4.98984e-4 0.000402836 -1.23868   2.15464e- 1 790705
 12 Gravettian Sunghir          BachoKiro_IUP Onge_Jarawa    4.72597e-4 0.000297432  1.58892   1.12078e- 1 790705
 13 Gravettian BachoKiro_BK1653 BachoKiro_IUP Ust_Ishim     -1.14378e-3 0.000537457 -2.12814   3.33255e- 2 790705
 14 Gravettian Sunghir          BachoKiro_IUP Ust_Ishim      1.27743e-4 0.000383711  0.332914  7.39199e- 1 790705
 15 Gravettian BachoKiro_BK1653 BachoKiro_IUP ZlatyKun      -7.02349e-4 0.000547966 -1.28174   1.99934e- 1 790705
 16 Gravettian Sunghir          BachoKiro_IUP ZlatyKun       1.20423e-4 0.000371439  0.324206  7.45782e- 1 790705
And so on cycling each right pop into the pop3 position.

The model passes with Gravettian as a ~49/51 mix of BK1653/Sunghir.
$weights
 A tibble: 2 x 5
  target     left               weight        se       z
  <chr>      <chr>               <dbl>     <dbl>   <dbl>
1 Gravettian BachoKiro_BK1653 0.493855 0.0595271 8.29630
2 Gravettian Sunghir          0.506145 0.0595271 8.50277

$rankdrop
 A tibble: 2 x 7
  f4rank   dof     chisq           p dofdiff chisqdiff     p_nested
   <int> <int>     <dbl>       <dbl>   <int>     <dbl>        <dbl>
1      1     7   8.38881 2.99560e- 1       9   130.551  9.13563e-24

Ideally what I am hoping to be able to see are f4 stats that show something like...
Pop1: First right pop / 'outgroup' (in this case Mbuti)
Pop2: Each additional right pop 
Pop3: Gravettian
Pop4: A simulated 49/51 mix of BK1653/Sunghir

Since the model passed, I would expect each of those hypothetical F4 stats to be reasonably close to 0.
If however, WHG were added to the right pops, the model will fail, and the hypothetical F4 stat...
Mbuti WHG Gravettian Model
Should be significantly negative, as WHG are much more related to Gravettians (Vestonice, Krems, Ostuni) than to either BK1653 or Sunghir.

Qpgraph outputs something of a very similar nature, albeit with f3 stats, which I find indispensibly useful. 
    pop1  pop2                     pop3                        est        se    fit         diff        z       p
    <chr> <chr>                    <chr>                     <dbl>     <dbl>  <dbl>        <dbl>    <dbl>   <dbl>
  1 Mbuti ZlatyKun                 ZlatyKun                 0.3109 0.0005686 0.3105  0.0003480    0.6120  0.5405 
  2 Mbuti ZlatyKun                 Ust_Ishim                0.1724 0.0007519 0.1730 -0.0006269   -0.8338  0.4044 
  3 Mbuti ZlatyKun                 BachoKiro_IUP            0.1721 0.0006559 0.1719  0.0001776    0.2707  0.7866

**Comment by uqrmaie1** [comment]
Did you try this with the latest version? You should get additional lines in the f4 output table, with pop2 = fit.

**Comment by Kale-GA** [comment]
That was with Version 2.0.8, which is the newest right?
When using f2_from_precomp as data source, the additional fit lines are present (this has been true since Version 2.0.0)
    pop1       pop2             pop3          pop4                  est          se           z           p    weight
    <chr>      <chr>            <chr>         <chr>               <dbl>       <dbl>       <dbl>       <dbl>     <dbl>
  1 Gravettian BachoKiro_BK1653 BachoKiro_IUP China_UP      -9.21438e-4 0.000451366 -2.04144    4.12067e- 2  0.495560
  2 Gravettian fit              BachoKiro_IUP China_UP      -3.12947e-4 0.000303372 -1.03156    3.02279e- 1 NA       
  3 Gravettian Sunghir          BachoKiro_IUP China_UP       2.84833e-4 0.000312566  0.911276   3.62150e- 1  0.504440
Fit lines are not present when using genotype data however.

**Comment by uqrmaie1** [comment]
Yes, 2.0.8 is the latest version. Not sure why you don't get the fitted f4-stats, it works with my test datasets.
Could you run `sessionInfo()` in R and send me the output?
And could you also share your dataset with me, or a downsampled version of it?

**Comment by Kale-GA** [comment]
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.4      admixtools_2.0.8

loaded via a namespace (and not attached):
 [1] gtable_0.3.5     compiler_4.4.1   crayon_1.5.3     tidyselect_1.2.1 Rcpp_1.0.13      stringr_1.5.1    tidyr_1.1.2      scales_1.3.0     ggplot2_3.5.1    readr_1.4.0     
[11] R6_2.5.1         generics_0.1.3   igraph_1.2.6     iterators_1.0.14 tibble_3.2.1     munsell_0.5.1    DBI_1.2.3        pillar_1.9.0     rlang_1.1.4      utf8_1.2.4      
[21] stringi_1.8.4    cli_3.6.3        withr_3.0.1      magrittr_2.0.3   foreach_1.5.2    grid_4.4.1       hms_1.1.3        lifecycle_1.0.4  vctrs_0.6.5      glue_1.8.0      
[31] codetools_0.2-20 abind_1.4-8      fansi_1.0.6      colorspace_2.0-0 purrr_1.0.2      tools_4.4.1      pkgconfig_2.0.3  ellipsis_0.3.2  
> 

And here's the datatset I was using for the example, it's a very trimmed down version I use for qpgraph, but I've tested with my full dataset too, same behavior.
https://ufile.io/tlzosbub

**Comment by uqrmaie1** [comment]
It should work if you update dplyr to version 1.1.4!

**Comment by Kale-GA** [comment]
That did it! Thank you very much.
