### ISSUE TITLE
Results not matching with admix1 

### ISSUE THREAD

**Issue by Maroc2567** [uqrmaie1/admixtools#82]
admix1

[code]qpAdm: parameter file: parqpAdm
### THE INPUT PARAMETERS
##PARAMETER NAME: VALUE
DIR: v62_0_Tofa
indivname: v62_0_Tofa.ind
snpname: v62_0_Tofa.snp
genotypename: v62_0_Tofa.geno
popleft: left1
popright: right1
details: YES
allsnps: YES
inbreed: NO
## qpAdm version: 2050
seed: 1637545365
inbreed set NO
tmp: /tmp/fsx.4077

left pops:
                Son      1
        Mozabite.DG    22
          Yoruba.DG    21

right pops:
            Mbuti.DG    14
Turkey_Marmara_Barcin_N.SG      3
Georgia_Kotias_Mesolithic.SG      2
  Morocco_SKH_MN.SG      3
Morocco_OUB_EpiP.SG      1
          Spain_C.SG    10
Russia_Afanasievo.SG      5
Italy_Epigravettian.SG      4
Russia_YuzhniyOleniyOstrov_Mesolithic.SG      1
Kazakhstan_Botai_Eneolithic.SG      3
India_GreatAndaman_100BP.SG      1
Russia_DevilsCave_N.SG      4
Peru_RioUncallane_1600BP.SG      3
  Levant_Natufian.AG      6
        Iraq_PPNA.AG      2

codimension 1
f4info: 
f4rank: 1 dof:    13 chisq:    18.586 tail:          0.136493468 dofdiff:    15 chisqdiff:  -18.586 taildiff:                    1
B:
          scale    1.000 
Turkey_Marmara_Barcin_N.SG    1.146 
Georgia_Kotias_Mesolithic.SG    1.013 
Morocco_SKH_MN.SG    1.038 
Morocco_OUB_EpiP.SG    0.851 
    Spain_C.SG    1.136 
Russia_Afanasievo.SG    1.037 
Italy_Epigravettian.SG    1.080 
Russia_YuzhniyOleniyOstrov_Mesolithic.SG    1.028 
Kazakhstan_Botai_Eneolithic.SG    0.970 
India_GreatAndaman_100BP.SG    0.825 
Russia_DevilsCave_N.SG    0.838 
Peru_RioUncallane_1600BP.SG    0.892 
Levant_Natufian.AG    1.045 
  Iraq_PPNA.AG    1.029 
A:
          scale    13.646 
    Mozabite.DG    0.080 
      Yoruba.DG    -1.412 

full rank
f4info: 
f4rank: 2 dof:      0 chisq:    0.000 tail:                    1 dofdiff:    13 chisqdiff:    18.586 taildiff:          0.136493468
B:
          scale  154.200    9.669 
Turkey_Marmara_Barcin_N.SG    1.042    -1.147 
Georgia_Kotias_Mesolithic.SG    0.908    -1.020 
Morocco_SKH_MN.SG    1.018    -1.033 
Morocco_OUB_EpiP.SG    0.811    -0.849 
    Spain_C.SG    1.065    -1.136 
Russia_Afanasievo.SG    1.001    -1.040 
Italy_Epigravettian.SG    0.891    -1.088 
Russia_YuzhniyOleniyOstrov_Mesolithic.SG    1.275    -1.015 
Kazakhstan_Botai_Eneolithic.SG    1.021    -0.970 
India_GreatAndaman_100BP.SG    0.716    -0.833 
Russia_DevilsCave_N.SG    0.582    -0.858 
Peru_RioUncallane_1600BP.SG    0.825    -0.899 
Levant_Natufian.AG    0.970    -1.044 
  Iraq_PPNA.AG    1.524    -0.999 
A:
          scale    1.414    1.414 
    Mozabite.DG    1.414    0.000 
      Yoruba.DG    0.000    1.414 

best coefficients:    0.946    0.054 
totmean:      0.946    0.054 
zzevarboot
    0.920655124    0.079344876 
    0.008748840 
  -0.101514619 
zzevarboot2
    0.970506644    0.029493356 
    0.003197328 
  -0.105211091 
boot mean:    0.946    0.054 
bootstrap saimpling of F-coeffs: 1000
zzjmean    0.946    0.054 
      std. errors:    0.014    0.014 

error covariance (* 1,000,000)
      187      -187 
      -187        187 

summ: Son    2      0.136493    0.946    0.054        187      -187        187 

    fixed pat  wt  dof    chisq      tail prob
          00  0    13    18.586        0.136493    0.946    0.054 
          01  1    14    33.456      0.00247521    1.000    0.000 
          10  1    14  3854.515              0    0.000    1.000 
best pat:          00        0.136493              -  -
best pat:          01      0.00247521  chi(nested):    14.869 p-value for nested model:    0.000115219

coeffs:    0.946    0.054 

## genstat:: f_4(Base, Fit, right1, right2)

details:          Mozabite.DG Turkey_Marmara_Barcin_N.SG    0.006761    3.625896
details:            Yoruba.DG Turkey_Marmara_Barcin_N.SG    -0.118646  -57.832780
dscore: Turkey_Marmara_Barcin_N.SG f4:    0.000032 Z:    0.017152

details:          Mozabite.DG Georgia_Kotias_Mesolithic.SG    0.005889    3.306462
details:            Yoruba.DG Georgia_Kotias_Mesolithic.SG    -0.105456  -53.245845
dscore: Georgia_Kotias_Mesolithic.SG f4:    -0.000085 Z:    -0.047825

details:          Mozabite.DG    Morocco_SKH_MN.SG    0.006605    3.728903
details:            Yoruba.DG    Morocco_SKH_MN.SG    -0.106878  -54.046343
dscore:    Morocco_SKH_MN.SG f4:    0.000516 Z:    0.292321

details:          Mozabite.DG  Morocco_OUB_EpiP.SG    0.005259    2.982602
details:            Yoruba.DG  Morocco_OUB_EpiP.SG    -0.087849  -43.148792
dscore:  Morocco_OUB_EpiP.SG f4:    0.000263 Z:    0.149385

details:          Mozabite.DG          Spain_C.SG    0.006905    3.700702
details:            Yoruba.DG          Spain_C.SG    -0.117532  -57.880421
dscore:          Spain_C.SG f4:    0.000228 Z:    0.122767

details:          Mozabite.DG Russia_Afanasievo.SG    0.006494    3.693838
details:            Yoruba.DG Russia_Afanasievo.SG    -0.107596  -54.613819
dscore: Russia_Afanasievo.SG f4:    0.000373 Z:    0.212631

details:          Mozabite.DG Italy_Epigravettian.SG    0.005781    2.946846
details:            Yoruba.DG Italy_Epigravettian.SG    -0.112568  -51.774812
dscore: Italy_Epigravettian.SG f4:    -0.000569 Z:    -0.290946

details:          Mozabite.DG Russia_YuzhniyOleniyOstrov_Mesolithic.SG    0.008268    4.011479
details:            Yoruba.DG Russia_YuzhniyOleniyOstrov_Mesolithic.SG    -0.104956  -46.087593
dscore: Russia_YuzhniyOleniyOstrov_Mesolithic.SG f4:    0.002193 Z:    1.066968

details:          Mozabite.DG Kazakhstan_Botai_Eneolithic.SG    0.006619    3.822790
details:            Yoruba.DG Kazakhstan_Botai_Eneolithic.SG    -0.100313  -51.076673
dscore: Kazakhstan_Botai_Eneolithic.SG f4:    0.000882 Z:    0.510238

details:          Mozabite.DG India_GreatAndaman_100BP.SG    0.004646    2.567820
details:            Yoruba.DG India_GreatAndaman_100BP.SG    -0.086134  -42.724499
dscore: India_GreatAndaman_100BP.SG f4:    -0.000225 Z:    -0.124775

details:          Mozabite.DG Russia_DevilsCave_N.SG    0.003776    2.294647
details:            Yoruba.DG Russia_DevilsCave_N.SG    -0.088736  -45.945293
dscore: Russia_DevilsCave_N.SG f4:    -0.001187 Z:    -0.722280

details:          Mozabite.DG Peru_RioUncallane_1600BP.SG    0.005348    3.126498
details:            Yoruba.DG Peru_RioUncallane_1600BP.SG    -0.092994  -46.817977
dscore: Peru_RioUncallane_1600BP.SG f4:    0.000072 Z:    0.042050

details:          Mozabite.DG  Levant_Natufian.AG    0.006292    3.145839
details:            Yoruba.DG  Levant_Natufian.AG    -0.108022  -49.741260
dscore:  Levant_Natufian.AG f4:    0.000158 Z:    0.079539

details:          Mozabite.DG        Iraq_PPNA.AG    0.009882    4.691660
details:            Yoruba.DG        Iraq_PPNA.AG    -0.103274  -45.361903
dscore:        Iraq_PPNA.AG f4:    0.003811 Z:    1.815844

gendstat:            Mbuti.DG Turkey_Marmara_Barcin_N.SG    0.017
gendstat:            Mbuti.DG Georgia_Kotias_Mesolithic.SG    -0.048
gendstat:            Mbuti.DG    Morocco_SKH_MN.SG    0.292
gendstat:            Mbuti.DG  Morocco_OUB_EpiP.SG    0.149
gendstat:            Mbuti.DG          Spain_C.SG    0.123
gendstat:            Mbuti.DG Russia_Afanasievo.SG    0.213
gendstat:            Mbuti.DG Italy_Epigravettian.SG    -0.291
gendstat:            Mbuti.DG Russia_YuzhniyOleniyOstrov_Mesolithic.SG    1.067
gendstat:            Mbuti.DG Kazakhstan_Botai_Eneolithic.SG    0.510
gendstat:            Mbuti.DG India_GreatAndaman_100BP.SG    -0.125
gendstat:            Mbuti.DG Russia_DevilsCave_N.SG    -0.722
gendstat:            Mbuti.DG Peru_RioUncallane_1600BP.SG    0.042
gendstat:            Mbuti.DG  Levant_Natufian.AG    0.080
gendstat:            Mbuti.DG        Iraq_PPNA.AG    1.816
gendstat: Turkey_Marmara_Barcin_N.SG Georgia_Kotias_Mesolithic.SG    -0.093
gendstat: Turkey_Marmara_Barcin_N.SG    Morocco_SKH_MN.SG    0.413
gendstat: Turkey_Marmara_Barcin_N.SG  Morocco_OUB_EpiP.SG    0.127
gendstat: Turkey_Marmara_Barcin_N.SG          Spain_C.SG    0.229
gendstat: Turkey_Marmara_Barcin_N.SG Russia_Afanasievo.SG    0.321
gendstat: Turkey_Marmara_Barcin_N.SG Italy_Epigravettian.SG    -0.474
gendstat: Turkey_Marmara_Barcin_N.SG Russia_YuzhniyOleniyOstrov_Mesolithic.SG    1.490
gendstat: Turkey_Marmara_Barcin_N.SG Kazakhstan_Botai_Eneolithic.SG    0.707
gendstat: Turkey_Marmara_Barcin_N.SG India_GreatAndaman_100BP.SG    -0.175
gendstat: Turkey_Marmara_Barcin_N.SG Russia_DevilsCave_N.SG    -0.905
gendstat: Turkey_Marmara_Barcin_N.SG Peru_RioUncallane_1600BP.SG    0.031
gendstat: Turkey_Marmara_Barcin_N.SG  Levant_Natufian.AG    0.090
gendstat: Turkey_Marmara_Barcin_N.SG        Iraq_PPNA.AG    2.615
gendstat: Georgia_Kotias_Mesolithic.SG    Morocco_SKH_MN.SG    0.445
gendstat: Georgia_Kotias_Mesolithic.SG  Morocco_OUB_EpiP.SG    0.189
gendstat: Georgia_Kotias_Mesolithic.SG          Spain_C.SG    0.261
gendstat: Georgia_Kotias_Mesolithic.SG Russia_Afanasievo.SG    0.422
gendstat: Georgia_Kotias_Mesolithic.SG Italy_Epigravettian.SG    -0.343
gendstat: Georgia_Kotias_Mesolithic.SG Russia_YuzhniyOleniyOstrov_Mesolithic.SG    1.507
gendstat: Georgia_Kotias_Mesolithic.SG Kazakhstan_Botai_Eneolithic.SG    0.814
gendstat: Georgia_Kotias_Mesolithic.SG India_GreatAndaman_100BP.SG    -0.092
gendstat: Georgia_Kotias_Mesolithic.SG Russia_DevilsCave_N.SG    -0.777
gendstat: Georgia_Kotias_Mesolithic.SG Peru_RioUncallane_1600BP.SG    0.119
gendstat: Georgia_Kotias_Mesolithic.SG  Levant_Natufian.AG    0.152
gendstat: Georgia_Kotias_Mesolithic.SG        Iraq_PPNA.AG    2.479
gendstat:    Morocco_SKH_MN.SG  Morocco_OUB_EpiP.SG    -0.147
gendstat:    Morocco_SKH_MN.SG          Spain_C.SG    -0.245
gendstat:    Morocco_SKH_MN.SG Russia_Afanasievo.SG    -0.115
gendstat:    Morocco_SKH_MN.SG Italy_Epigravettian.SG    -0.744
gendstat:    Morocco_SKH_MN.SG Russia_YuzhniyOleniyOstrov_Mesolithic.SG    1.056
gendstat:    Morocco_SKH_MN.SG Kazakhstan_Botai_Eneolithic.SG    0.276
gendstat:    Morocco_SKH_MN.SG India_GreatAndaman_100BP.SG    -0.483
gendstat:    Morocco_SKH_MN.SG Russia_DevilsCave_N.SG    -1.229
gendstat:    Morocco_SKH_MN.SG Peru_RioUncallane_1600BP.SG    -0.321
gendstat:    Morocco_SKH_MN.SG  Levant_Natufian.AG    -0.244
gendstat:    Morocco_SKH_MN.SG        Iraq_PPNA.AG    2.049
gendstat:  Morocco_OUB_EpiP.SG          Spain_C.SG    -0.019
gendstat:  Morocco_OUB_EpiP.SG Russia_Afanasievo.SG    0.063
gendstat:  Morocco_OUB_EpiP.SG Italy_Epigravettian.SG    -0.439
gendstat:  Morocco_OUB_EpiP.SG Russia_YuzhniyOleniyOstrov_Mesolithic.SG    0.976
gendstat:  Morocco_OUB_EpiP.SG Kazakhstan_Botai_Eneolithic.SG    0.350
gendstat:  Morocco_OUB_EpiP.SG India_GreatAndaman_100BP.SG    -0.252
gendstat:  Morocco_OUB_EpiP.SG Russia_DevilsCave_N.SG    -0.842
gendstat:  Morocco_OUB_EpiP.SG Peru_RioUncallane_1600BP.SG    -0.111
gendstat:  Morocco_OUB_EpiP.SG  Levant_Natufian.AG    -0.055
gendstat:  Morocco_OUB_EpiP.SG        Iraq_PPNA.AG    1.734
gendstat:          Spain_C.SG Russia_Afanasievo.SG    0.154
gendstat:          Spain_C.SG Italy_Epigravettian.SG    -0.731
gendstat:          Spain_C.SG Russia_YuzhniyOleniyOstrov_Mesolithic.SG    1.455
gendstat:          Spain_C.SG Kazakhstan_Botai_Eneolithic.SG    0.608
gendstat:          Spain_C.SG India_GreatAndaman_100BP.SG    -0.319
gendstat:          Spain_C.SG Russia_DevilsCave_N.SG    -1.118
gendstat:          Spain_C.SG Peru_RioUncallane_1600BP.SG    -0.130
gendstat:          Spain_C.SG  Levant_Natufian.AG    -0.051
gendstat:          Spain_C.SG        Iraq_PPNA.AG    2.447
gendstat: Russia_Afanasievo.SG Italy_Epigravettian.SG    -0.793
gendstat: Russia_Afanasievo.SG Russia_YuzhniyOleniyOstrov_Mesolithic.SG    1.392
gendstat: Russia_Afanasievo.SG Kazakhstan_Botai_Eneolithic.SG    0.552
gendstat: Russia_Afanasievo.SG India_GreatAndaman_100BP.SG    -0.433
gendstat: Russia_Afanasievo.SG Russia_DevilsCave_N.SG    -1.316
gendstat: Russia_Afanasievo.SG Peru_RioUncallane_1600BP.SG    -0.268
gendstat: Russia_Afanasievo.SG  Levant_Natufian.AG    -0.147
gendstat: Russia_Afanasievo.SG        Iraq_PPNA.AG    2.361
gendstat: Italy_Epigravettian.SG Russia_YuzhniyOleniyOstrov_Mesolithic.SG    1.973
gendstat: Italy_Epigravettian.SG Kazakhstan_Botai_Eneolithic.SG    1.178
gendstat: Italy_Epigravettian.SG India_GreatAndaman_100BP.SG    0.217
gendstat: Italy_Epigravettian.SG Russia_DevilsCave_N.SG    -0.430
gendstat: Italy_Epigravettian.SG Peru_RioUncallane_1600BP.SG    0.456
gendstat: Italy_Epigravettian.SG  Levant_Natufian.AG    0.445
gendstat: Italy_Epigravettian.SG        Iraq_PPNA.AG    2.601
gendstat: Russia_YuzhniyOleniyOstrov_Mesolithic.SG Kazakhstan_Botai_Eneolithic.SG    -1.019
gendstat: Russia_YuzhniyOleniyOstrov_Mesolithic.SG India_GreatAndaman_100BP.SG    -1.428
gendstat: Russia_YuzhniyOleniyOstrov_Mesolithic.SG Russia_DevilsCave_N.SG    -2.240
gendstat: Russia_YuzhniyOleniyOstrov_Mesolithic.SG Peru_RioUncallane_1600BP.SG    -1.519
gendstat: Russia_YuzhniyOleniyOstrov_Mesolithic.SG  Levant_Natufian.AG    -1.151
gendstat: Russia_YuzhniyOleniyOstrov_Mesolithic.SG        Iraq_PPNA.AG    0.864
gendstat: Kazakhstan_Botai_Eneolithic.SG India_GreatAndaman_100BP.SG    -0.816
gendstat: Kazakhstan_Botai_Eneolithic.SG Russia_DevilsCave_N.SG    -1.819
gendstat: Kazakhstan_Botai_Eneolithic.SG Peru_RioUncallane_1600BP.SG    -0.798
gendstat: Kazakhstan_Botai_Eneolithic.SG  Levant_Natufian.AG    -0.485
gendstat: Kazakhstan_Botai_Eneolithic.SG        Iraq_PPNA.AG    1.810
gendstat: India_GreatAndaman_100BP.SG Russia_DevilsCave_N.SG    -0.692
gendstat: India_GreatAndaman_100BP.SG Peru_RioUncallane_1600BP.SG    0.222
gendstat: India_GreatAndaman_100BP.SG  Levant_Natufian.AG    0.222
gendstat: India_GreatAndaman_100BP.SG        Iraq_PPNA.AG    2.255
gendstat: Russia_DevilsCave_N.SG Peru_RioUncallane_1600BP.SG    1.153
gendstat: Russia_DevilsCave_N.SG  Levant_Natufian.AG    0.853
gendstat: Russia_DevilsCave_N.SG        Iraq_PPNA.AG    2.858
gendstat: Peru_RioUncallane_1600BP.SG  Levant_Natufian.AG    0.057
gendstat: Peru_RioUncallane_1600BP.SG        Iraq_PPNA.AG    2.272
gendstat:  Levant_Natufian.AG        Iraq_PPNA.AG    2.023

worst Z-score with right hand mix
f4(Target, Fit, Base, mix of Right pops;  Z:    -4.062 sum:    1.000
    Turkey_Marmara_Barcin_N.SG    5.076
  Georgia_Kotias_Mesolithic.SG    4.873
            Morocco_SKH_MN.SG    -1.479
          Morocco_OUB_EpiP.SG    0.020
                    Spain_C.SG    -0.586
          Russia_Afanasievo.SG    2.201
        Italy_Epigravettian.SG    6.660
Russia_YuzhniyOleniyOstrov_Mesolithic.SG    -8.642
Kazakhstan_Botai_Eneolithic.SG    -7.604
  India_GreatAndaman_100BP.SG    1.181
        Russia_DevilsCave_N.SG    7.944
  Peru_RioUncallane_1600BP.SG    1.982
            Levant_Natufian.AG    0.278
                  Iraq_PPNA.AG  -10.903

removing /tmp/fsx.4077
oldmode set: terminating
##end of qpAdm:        1.537 seconds cpu        6.918 Mbytes in use[/code]

admix2 

[code]> prefix = "C:/Users/fromh/v62_0_Tofa" 
> 
> 
> left=c('Mozabite.DG', 'Yoruba.DG') 
> 
> right=c('Mbuti.DG', 'Turkey_Marmara_Barcin_N.SG', 'Georgia_Kotias_Mesolithic.SG', 'Morocco_SKH_MN.SG', 'Morocco_OUB_EpiP.SG', 'Spain_C.SG', 'Russia_Afanasievo.SG', 'Italy_Epigravettian.SG', 'Russia_YuzhniyOleniyOstrov_Mesolithic.SG', 'Kazakhstan_Botai_Eneolithic.SG', 'India_GreatAndaman_100BP.SG', 'Russia_DevilsCave_N.SG', 'Peru_RioUncallane_1600BP.SG', 'Levant_Natufian.AG', 'Iraq_PPNA.AG') 
> target='Son'
> qp=qpadm("C:/Users/fromh/v62_0_Tofa",left,right,target,allsnps=TRUE)
ℹ Reading metadata...
ℹ Computing block lengths for 1150639 SNPs...
ℹ Computing 28 f4-statistics for block 713 out of 713...
ℹ "allsnps = TRUE" uses different SNPs for each f4-statistic
  Number of SNPs used for each f4-statistic:
   pop1        pop2     pop3                                     pop4      n
1   Son Mozabite.DG Mbuti.DG             Georgia_Kotias_Mesolithic.SG 597598
2   Son Mozabite.DG Mbuti.DG              India_GreatAndaman_100BP.SG 588925
3   Son Mozabite.DG Mbuti.DG                             Iraq_PPNA.AG 187179
4   Son Mozabite.DG Mbuti.DG                   Italy_Epigravettian.SG 594675
5   Son Mozabite.DG Mbuti.DG           Kazakhstan_Botai_Eneolithic.SG 597646
6   Son Mozabite.DG Mbuti.DG                       Levant_Natufian.AG 104189
7   Son Mozabite.DG Mbuti.DG                      Morocco_OUB_EpiP.SG 597596
8   Son Mozabite.DG Mbuti.DG                        Morocco_SKH_MN.SG 596064
9   Son Mozabite.DG Mbuti.DG              Peru_RioUncallane_1600BP.SG 597594
10  Son Mozabite.DG Mbuti.DG                     Russia_Afanasievo.SG 596598
11  Son Mozabite.DG Mbuti.DG                   Russia_DevilsCave_N.SG 597455
12  Son Mozabite.DG Mbuti.DG Russia_YuzhniyOleniyOstrov_Mesolithic.SG 515751
13  Son Mozabite.DG Mbuti.DG                               Spain_C.SG 597690
14  Son Mozabite.DG Mbuti.DG               Turkey_Marmara_Barcin_N.SG 597679
15  Son   Yoruba.DG Mbuti.DG             Georgia_Kotias_Mesolithic.SG 597596
16  Son   Yoruba.DG Mbuti.DG              India_GreatAndaman_100BP.SG 588923
17  Son   Yoruba.DG Mbuti.DG                             Iraq_PPNA.AG 187177
18  Son   Yoruba.DG Mbuti.DG                   Italy_Epigravettian.SG 594673
19  Son   Yoruba.DG Mbuti.DG           Kazakhstan_Botai_Eneolithic.SG 597644
20  Son   Yoruba.DG Mbuti.DG                       Levant_Natufian.AG 104188
21  Son   Yoruba.DG Mbuti.DG                      Morocco_OUB_EpiP.SG 597593
22  Son   Yoruba.DG Mbuti.DG                        Morocco_SKH_MN.SG 596062
23  Son   Yoruba.DG Mbuti.DG              Peru_RioUncallane_1600BP.SG 597592
24  Son   Yoruba.DG Mbuti.DG                     Russia_Afanasievo.SG 596596
25  Son   Yoruba.DG Mbuti.DG                   Russia_DevilsCave_N.SG 597453
26  Son   Yoruba.DG Mbuti.DG Russia_YuzhniyOleniyOstrov_Mesolithic.SG 515746
27  Son   Yoruba.DG Mbuti.DG                               Spain_C.SG 597688
28  Son   Yoruba.DG Mbuti.DG               Turkey_Marmara_Barcin_N.SG 597677
ℹ Computing admixture weights...
ℹ Computing standard errors...
ℹ Computing number of admixture waves...
> 
> qp$weights
# A tibble: 2 × 5
  target left        weight     se     z
  <chr>  <chr>        <dbl>  <dbl> <dbl>
1 Son    Mozabite.DG 0.939  0.0135 69.7 
2 Son    Yoruba.DG   0.0615 0.0135  4.57
> qp$popdrop
# A tibble: 3 × 13
  pat      wt   dof   chisq        p f4rank Mozabite.DG Yoruba.DG feasible best  dofdiff chisqdiff p_nested
  <chr> <dbl> <dbl>   <dbl>    <dbl>  <dbl>       <dbl>     <dbl> <lgl>    <lgl>   <dbl>     <dbl>    <dbl>
1 00        0    13    48.5 5.45e- 6      1       0.939    0.0615 TRUE     NA         NA       NA        NA
2 01        1    14   116.  4.27e-18      0       1       NA      TRUE     TRUE        0   -13224.        1
3 10        1    14 13339.  0             0      NA        1      TRUE     TRUE       NA       NA        NA
> 
> `|`=`%>%`
> p=""
> o=""
> rm(t)
Warning message:
In rm(t) : object 't' not found
> #t=qp$popdrop|dplyr::filter(f4rank!=0&feasible)|arrange(desc(p),chisq)
> t=qp$popdrop|dplyr::filter(f4rank!=0&feasible)|arrange(desc(p),chisq)
> 
> p=t|select(7:last_col(5))|apply(1,\(x)na.omit(100*x)|sort(T)|sprintf("%.0f %s",.,names(.))|paste(collapse=" "))
> o=sub("^0","",sprintf(ifelse(t$p<.001,"%.0g","%.3f"),t$p))|paste0((ifelse(t$p > 0.05,"SUCCESS ","FAILED  ")),"p=",.," ",p,collapse="\n")
> paste0("Target: ",target,"\nLeft: ",paste(sort(left),collapse=", "),"\nRight: ",paste(right,collapse=", "),"\nFeasible Results:","\n",o)|writeLines
Target: Son
Left: Mozabite.DG, Yoruba.DG
Right: Mbuti.DG, Turkey_Marmara_Barcin_N.SG, Georgia_Kotias_Mesolithic.SG, Morocco_SKH_MN.SG, Morocco_OUB_EpiP.SG, Spain_C.SG, Russia_Afanasievo.SG, Italy_Epigravettian.SG, Russia_YuzhniyOleniyOstrov_Mesolithic.SG, Kazakhstan_Botai_Eneolithic.SG, India_GreatAndaman_100BP.SG, Russia_DevilsCave_N.SG, Peru_RioUncallane_1600BP.SG, Levant_Natufian.AG, Iraq_PPNA.AG
Feasible Results:
FAILED  p=5e-06 94 Mozabite.DG 6 Yoruba.DG[/code]

code I used for admix2  

[code]prefix = "C:/Users/fromh/v62_0_Tofa" 

 
left=c('Mozabite.DG', 'Yoruba.DG') 

right=c('Mbuti.DG', 'Turkey_Marmara_Barcin_N.SG', 'Georgia_Kotias_Mesolithic.SG', 'Morocco_SKH_MN.SG', 'Morocco_OUB_EpiP.SG', 'Spain_C.SG', 'Russia_Afanasievo.SG', 'Italy_Epigravettian.SG', 'Russia_YuzhniyOleniyOstrov_Mesolithic.SG', 'Kazakhstan_Botai_Eneolithic.SG', 'India_GreatAndaman_100BP.SG', 'Russia_DevilsCave_N.SG', 'Peru_RioUncallane_1600BP.SG', 'Levant_Natufian.AG', 'Iraq_PPNA.AG') 
target='Son'
qp=qpadm("C:/Users/fromh/v62_0_Tofa",left,right,target,allsnps=TRUE)

qp$weights
qp$popdrop

`|`=`%>%`
p=""
o=""
rm(t)
#t=qp$popdrop|dplyr::filter(f4rank!=0&feasible)|arrange(desc(p),chisq)
t=qp$popdrop|dplyr::filter(f4rank!=0&feasible)|arrange(desc(p),chisq)

p=t|select(7:last_col(5))|apply(1,\(x)na.omit(100*x)|sort(T)|sprintf("%.0f %s",.,names(.))|paste(collapse=" "))
o=sub("^0","",sprintf(ifelse(t$p<.001,"%.0g","%.3f"),t$p))|paste0((ifelse(t$p > 0.05,"SUCCESS ","FAILED  ")),"p=",.," ",p,collapse="\n")
paste0("Target: ",target,"\nLeft: ",paste(sort(left),collapse=", "),"\nRight: ",paste(right,collapse=", "),"\nFeasible Results:","\n",o)|writeLines[/code]

**Comment by uqrmaie1** [comment]
Try running it with these options:
```
qpadm("C:/Users/fromh/v62_0_Tofa",left,right,target, allsnps = TRUE, fudge_twice = TRUE)
qpadm("C:/Users/fromh/v62_0_Tofa",left,right,target, allsnps = FALSE, fudge_twice = TRUE)
```
Let me know if the results are still not matching! (They won't match perfectly, but they should be very similar.)

**Comment by Maroc2567** [comment]
> Try running it with these options:
> 
> ```
> qpadm("C:/Users/fromh/v62_0_Tofa",left,right,target, allsnps = TRUE, fudge_twice = TRUE)
> qpadm("C:/Users/fromh/v62_0_Tofa",left,right,target, allsnps = FALSE, fudge_twice = TRUE)
> ```
> 
> Let me know if the results are still not matching! (They won't match perfectly, but they should be very similar.)

Second option worked, but I don’t understand why I needed to put all snps to false when I have it set to yes admixtools1? 

prefix = "C:/Users/fromh/v62_0_Tofa"
>
>
> left=c('Mozabite.DG', 'Yoruba.DG')
>
> right=c('Mbuti.DG', 'Turkey_Marmara_Barcin_N.SG', 'Georgia_Kotias_Mesolithic.SG', 'Morocco_SKH_MN.SG', 'Morocco_OUB_EpiP.SG', 'Spain_C.SG', 'Russia_Afanasievo.SG', 'Italy_Epigravettian.SG', 'Russia_YuzhniyOleniyOstrov_Mesolithic.SG', 'Kazakhstan_Botai_Eneolithic.SG', 'India_GreatAndaman_100BP.SG', 'Russia_DevilsCave_N.SG', 'Peru_RioUncallane_1600BP.SG', 'Levant_Natufian.AG', 'Iraq_PPNA.AG')
> target='Son'
> qp=qpadm("C:/Users/fromh/v62_0_Tofa",left,right,target, allsnps = FALSE, fudge_twice = TRUE)
ℹ Reading metadata...
ℹ Computing block lengths for [1150639](tel:1150639) SNPs...
ℹ Computing 28 f4-statistics for block 713 out of 713...
ℹ Number of SNPs after excluding those with missing data: 38885
ℹ Computing admixture weights...
ℹ Computing standard errors...
ℹ Computing number of admixture waves...
>
> qp$weights
# A tibble: 2 × 5
  target left        weight     se     z
  <chr>  <chr>        <dbl>  <dbl> <dbl>
1 Son    Mozabite.DG 0.941  0.0173 54.3
2 Son    Yoruba.DG   0.0589 0.0173  3.39
> qp$popdrop
# A tibble: 3 × 13
  pat      wt   dof  chisq        p f4rank Mozabite.DG Yoruba.DG feasible best  dofdiff chisqdiff p_nested
  <chr> <dbl> <dbl>  <dbl>    <dbl>  <dbl>       <dbl>     <dbl> <lgl>    <lgl>   <dbl>     <dbl>    <dbl>
1 00        0    13   20.4 8.56e- 2      1       0.941    0.0589 TRUE     NA         NA       NA        NA
2 01        1    14   72.0 8.49e-10      0       1       NA      TRUE     TRUE        0    -5622.        1
3 10        1    14 5694.  0             0      NA        1      TRUE     TRUE       NA       NA        NA
>
> `|`=`%>%`
> p=""
> o=""
> rm(t)
> #t=qp$popdrop|dplyr::filter(f4rank!=0&feasible)|arrange(desc(p),chisq)
> t=qp$popdrop|dplyr::filter(f4rank!=0&feasible)|arrange(desc(p),chisq)
>
> p=t|select(7:last_col(5))|apply(1,\(x)na.omit(100*x)|sort(T)|sprintf("%.0f %s",.,names(.))|paste(collapse=" "))
> o=sub("^0","",sprintf(ifelse(t$p<.001,"%.0g","%.3f"),t$p))|paste0((ifelse(t$p > 0.05,"SUCCESS ","FAILED  ")),"p=",.," ",p,collapse="\n")
> paste0("Target: ",target,"\nLeft: ",paste(sort(left),collapse=", "),"\nRight: ",paste(right,collapse=", "),"\nFeasible Results:","\n",o)|writeLines
Target: Son
Left: Mozabite.DG, Yoruba.DG
Right: Mbuti.DG, Turkey_Marmara_Barcin_N.SG, Georgia_Kotias_Mesolithic.SG, Morocco_SKH_MN.SG, Morocco_OUB_EpiP.SG, Spain_C.SG, Russia_Afanasievo.SG, Italy_Epigravettian.SG, Russia_YuzhniyOleniyOstrov_Mesolithic.SG, Kazakhstan_Botai_Eneolithic.SG, India_GreatAndaman_100BP.SG, Russia_DevilsCave_N.SG, Peru_RioUncallane_1600BP.SG, Levant_Natufian.AG, Iraq_PPNA.AG
Feasible Results:
SUCCESS p=.086 94 Mozabite.DG 6 Yoruba.DG

Is it because admix1 is not detecting I have set all snps to yes?
